FROM node:16-alpine

WORKDIR app

ENV NODE_ENV=uat

ARG GITHUB_TOKEN

RUN npm config set "@tikivn:registry" "https://npm.pkg.github.com"
RUN npm config set "//npm.pkg.github.com/:_authToken" "${GITHUB_TOKEN}"

COPY package*.json ./

RUN npm install

COPY . .

ENTRYPOINT ["/bin/sh", "-c", "npm run start"]